name: Windows build

on:
  push:
    paths-ignore:
      - '.clang-format'
      - '.drone.star'
      - '.gitattributes'
      - '.gitignore'
      - '.gdbinit'
      - '.github/*'
      - '.github/workflows/Linux_build.yml'
      - '.github/*_TEMPLATE/**'
      - '*.md'
      - '*.yml'
      - '*.txt'
      - 'docs/**'
      - 'src/**/*_posix.*'
      - 'src/**/*_linux.*'
      - 'src/**/*_gnulinux.*'
      - 'src/**/*_x11.*'
      - 'src/**/*_gtk.*'
      - 'src/**/*_android.*'
      - 'src/**/*_mac.*'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - '.clang-format'
      - '.drone.star'
      - '.gitattributes'
      - '.gitignore'
      - '.gdbinit'
      - '.github/*'
      - '.github/workflows/Linux_build.yml'
      - '.github/*_TEMPLATE/**'
      - '*.md'
      - '*.yml'
      - '*.txt'
      - 'docs/**'
      - 'src/**/*_posix.*'
      - 'src/**/*_linux.*'
      - 'src/**/*_gnulinux.*'
      - 'src/**/*_x11.*'
      - 'src/**/*_gtk.*'
      - 'src/**/*_android.*'
      - 'src/**/*_mac.*'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-11-arm
    env:
      POWERSHELL_TELEMETRY_OPTOUT: 1
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Setup
        run: .\xb setup
      - name: Build
        run: .\xb build --config=Checked --target=src\xenia-app --arch=ARM64
      - name: Prepare artifacts
        id: prepare_artifacts
        run: |
          foreach ($file in 'build\bin\Windows-ARM64','build\bin\Windows') {
            if ((get-item $file).Length -le 100000) {
              echo "::error::$file is too small."
            }
          }
          robocopy . build\bin\                                                             xenia_canary.exe   xenia_canary.pdb   LICENSE /r:0 /w:0
          robocopy   build\   xenia_canary.exe   xenia_canary.pdb   LICENSE /r:0 /w:0
      - name: Upload xenia canary artifacts
        if: steps.prepare_artifacts.outcome == 'success'
        uses: actions/upload-artifact@main
        with:
          name: xenia_canary_windows
          path: artifacts\xenia_canary
          if-no-files-found: error

  create-release:
    name: Create release
    needs: [build]
    if: |
      github.repository == 'xenia-canary/xenia-canary' &&
      github.event.action != 'pull_request' &&
      github.ref == 'refs/heads/canary_experimental'
    uses: ./.github/workflows/Create_release.yml
    with:
      os: windows
    secrets:
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
